services:
  db:
    image: postgres:16
    restart: always
    # These variables configure the database container itself
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    # This variable gives your Flask app the connection string
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    restart: always
    # This gives your Streamlit app the same connection string
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes:
  pgdata: